---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: TOBESET
  namespace: TOBESET
spec:
  clusterName: TOBESET
  clusterNamespace: TOBESET
  clusterLabels:
    name: TOBESET
    cluster.open-cluster-management.io/clusterset: TOBESET
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
